/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;
import controller.Controller;
import java.util.List;
import javax.swing.JOptionPane;
import model.*;
/**
 *
 * @author Korisnik
 */
public class UnosRadnikaForma extends javax.swing.JFrame {
    private Radnik odabrani;
    /**
     * Creates new form UnosRadnikaForma
     */
    public UnosRadnikaForma() {
        initComponents();
        popuniComboBox();
        jButtonIzmeni.setVisible(false);
        jButtonSacuvajIzmenu.setVisible(false);
        
    }
    public UnosRadnikaForma(Radnik r) {
        initComponents();
        popuniComboBox();
        odabrani=r;
        popuniFormu(odabrani);
        jButtonSacuvajIzmenu.setEnabled(false);
        jButtonSacuvaj.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRadnaKnjizica = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldJMBG = new javax.swing.JTextField();
        jComboBoxOJed = new javax.swing.JComboBox<>();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonSacuvajIzmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radna knjizica");

        jLabel2.setText("Ime");

        jLabel3.setText("Prezime");

        jLabel4.setText("JMBG");

        jLabel5.setText("Jedinica");

        jTextFieldIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Omoguci izmenu");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonSacuvajIzmenu.setText("Sacuvaj izmenu");
        jButtonSacuvajIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajIzmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButtonSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonIzmeni))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxOJed, 0, 154, Short.MAX_VALUE)
                            .addComponent(jTextFieldJMBG)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldIme)
                            .addComponent(jTextFieldRadnaKnjizica)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvajIzmenu)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRadnaKnjizica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxOJed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButtonSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmeni)
                    .addComponent(jButtonSacuvajIzmenu))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        
        Radnik r=validiraj();
        if(r==null){
            return;
        }
        int id=Controller.getInstance().ubaciRadnika(r);
        
        if(id>0){
            JOptionPane.showMessageDialog(this,"Dodat je radnik sa id-em: "+id);
        }else{
            JOptionPane.showMessageDialog(this, "Greska pri unosu radnika");
            return;
            
        }
        
        int odg=JOptionPane.showConfirmDialog(this, "Da li zelite da nastavnite ubacivanje?", "Provera", JOptionPane.YES_NO_OPTION);
        if(odg==JOptionPane.YES_OPTION){
            pripremiFormu();
        }else{
            this.dispose();
        }
        
        
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        
        jButtonSacuvajIzmenu.setEnabled(true);
          jTextFieldIme.setEnabled(true);
        jTextFieldJMBG.setEnabled(true);
        jTextFieldPrezime.setEnabled(true);
        jTextFieldRadnaKnjizica.setEnabled(true);
        jComboBoxOJed.setEnabled(true);
        
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonSacuvajIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajIzmenuActionPerformed
        
        Radnik novi=validiraj();
       
        if(novi==null){
            return;
        }
         novi.setId(odabrani.getId()); 
        int odg=JOptionPane.showConfirmDialog(this, "Da li zelite da sacuvate promene?", "Provera", JOptionPane.YES_NO_OPTION);
        
        if(odg==JOptionPane.YES_OPTION){
            boolean uspesno=Controller.getInstance().izmeniRadnika(novi);
            
            if(uspesno){
                StringBuilder sb=new StringBuilder();
                if(!novi.getRadnaKnjizica().equals(odabrani.getRadnaKnjizica())){
                    sb.append("Stara rk: "+odabrani.getRadnaKnjizica()+", nova rk: "+novi.getRadnaKnjizica()+"\n");
                }
                if(!novi.getJmbg().equals(odabrani.getJmbg())){
                    sb.append("Stari jmbg: "+odabrani.getJmbg()+", novi jmbg: "+novi.getJmbg()+"\n");
                }
                if(!novi.getIme().equals(odabrani.getIme())){
                    sb.append("Staro ime: "+odabrani.getIme()+", novo ime: "+novi.getIme()+"\n");
                }
                if(!novi.getPrezime().equals(odabrani.getPrezime())){
                    sb.append("Staro prezime: "+odabrani.getPrezime()+", novo prezime: "+novi.getPrezime()+"\n");
                }
                if(!novi.getOj().getNaziv().equals(odabrani.getOj().getNaziv())){
                    sb.append("Stara jedinica: "+odabrani.getOj().getNaziv()+", nova jedinica: "+novi.getOj().getNaziv()+"\n");
                }
                String poruka;
                if(sb.isEmpty()) poruka="nista nije promenjeno";
                poruka=sb.toString();
                JOptionPane.showMessageDialog(this, poruka);
            }
            else{
                JOptionPane.showMessageDialog(this, "Greska pri izmeni radnika");
            }
            
            
        }
        
        
        
    }//GEN-LAST:event_jButtonSacuvajIzmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosRadnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosRadnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosRadnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosRadnikaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosRadnikaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonSacuvajIzmenu;
    private javax.swing.JComboBox<OrganizacionaJedinica> jComboBoxOJed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldJMBG;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldRadnaKnjizica;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        
        List<OrganizacionaJedinica> lista=Controller.getInstance().vratiOJed();
        
        for(OrganizacionaJedinica o:lista){
            jComboBoxOJed.addItem(o);
        }
        lista.add(0,null);
    }

    private Radnik validiraj() {
        
        Radnik r=new Radnik();
        r.setId(0);
        if(jTextFieldRadnaKnjizica==null){
            return null;
        }
        String rk=jTextFieldRadnaKnjizica.getText();
        if(rk==null || rk.isEmpty() || rk.matches("[a-zA-Z]+") || rk.length()>10){
            JOptionPane.showMessageDialog(this, "Greska kod radne knjizice");
            return null;
        }
        
        r.setRadnaKnjizica(rk);
        if(jTextFieldIme==null){
            return null;
        }
        String ime=jTextFieldIme.getText();
        if(ime==null || ime.isEmpty() || !ime.matches("[a-zA-z]+") || ime.length()<2){
             JOptionPane.showMessageDialog(this, "Greska kod imena");
            return null;
        }
        r.setIme(ime);
        if(jTextFieldPrezime==null){
            return null;
        }
        String prezime=jTextFieldPrezime.getText();
        if(prezime==null || prezime.isEmpty() || !prezime.matches("[a-zA-z]+") || prezime.length()<2){
             JOptionPane.showMessageDialog(this, "Greska kod prezimena");
            return null;
        }
        r.setPrezime(prezime);
        if(jTextFieldJMBG==null){
            return null;
        }
        String jmbg=jTextFieldJMBG.getText();
        if(jmbg==null || jmbg.isEmpty() || jmbg.matches("[a-zA-z]+") || jmbg.length()!=13){
             JOptionPane.showMessageDialog(this, "Greska kod jmbg-a");
            return null;
        }
        r.setJmbg(jmbg);
        
        if(jComboBoxOJed.getSelectedItem()==null){
            return null;
        }
        OrganizacionaJedinica oj=(OrganizacionaJedinica) jComboBoxOJed.getSelectedItem();
        
        r.setOj(oj);
        
        return r;
    }

    private void pripremiFormu() {
        jTextFieldIme.setText("");
        jTextFieldJMBG.setText("");
        jTextFieldPrezime.setText("");
        jTextFieldRadnaKnjizica.setText("");
        jComboBoxOJed.setSelectedItem(null);
    }

    private void popuniFormu(Radnik r) {
        
        jTextFieldIme.setEnabled(false);
        jTextFieldJMBG.setEnabled(false);
        jTextFieldPrezime.setEnabled(false);
        jTextFieldRadnaKnjizica.setEnabled(false);
        jComboBoxOJed.setEnabled(false);
        
        
        jTextFieldIme.setText(r.getIme());
        jTextFieldJMBG.setText(r.getJmbg());
        jTextFieldPrezime.setText(r.getPrezime());
        jTextFieldRadnaKnjizica.setText(r.getRadnaKnjizica());
        jComboBoxOJed.setSelectedItem(r.getOj());
        
        
    }
}
